name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build_extension:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghidra: ['10.0.4', '10.1.1', '10.1.2', '10.1.3', '10.1.4']
        java:   ['11']
        include:
          - ghidra: '10.2.2'
            java:   '17'
          - ghidra: '10.2.3'
            java:   '17'
          - ghidra: '10.3.0'
            java:   '17'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin

      - name: Setup Ghidra
        uses: er28-0652/setup-ghidra@master
        with:
          version: ${{ matrix.ghidra }}

      - name: bodge
        run: chmod +x gradlew

      - name: Build Extension
        run: ./gradlew

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: dist/
          retention-days: 7

  push_release:
    if: |
      github.event_name == 'push' &&
      github.repository == 'clienthax/Ps3GhidraScripts'
    needs: build_extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create 1.0${{ GITHUB.RUN_NUMBER }} artifact/*.zip --target ${{ GITHUB.SHA }} -t 1.0${{ GITHUB.RUN_NUMBER }}

